### ISSUE TITLE
리프레시 토큰 정상적으로 동작하지 않는 이슈

### ISSUE THREAD

**Issue by eunsonny** [feedoong/feedoong-frontend#137]
<img width="1190" alt="스크린샷 2023-01-25 오후 10 47 52" src="https://user-images.githubusercontent.com/67362026/214580146-16952df4-7abe-4f20-8585-3edaedebffef.png">

**문제상황**
 - 피둥(로그인한 상태)을 켜놓은 상태에서 access token이 만료됨
 - access 토큰이 만료 되었으면, refresh 토큰으로 새로운 access 토큰을 발급받아야 하는데, 이 부분이 정상적으로 동작하지 않는 듯함. expired token 에러가 노출됨
 -  토큰이 만료되어 contents(내가 등록한 채널/ 내가 등록한 게시물)는 볼 수 없고, 다른 페이지로 이동하려 할 경우 /introduce로 리다이렉트 시키지만 기존에 받았던 userProfile 정보가 남아있어, 로그인 된 상태로 나타남 (GNB)
 -  로그아웃을 하려고 해도, 로그아웃은 현재 내 계정 페이지에서만 가능한데 토큰이 없기 때문에 내 계정 페이지로 가지 못하고 /introduce로 리다이렉트 됨
 - 새로고침을 하면 로그아웃 상태로 돌아옴

**Comment by saengmotmi** [comment]
~https://feedoong.slack.com/archives/C03U07MAP41/p1674835508633379 에서 1차 테스트~ 기각됨

**Comment by saengmotmi** [comment]
https://feedoong.slack.com/archives/C03KCD96T7W/p1676906175661409 의 이슈가 유력한 것으로 보임

**Comment by saengmotmi** [comment]
#161 + 서버 작업으로 해결
