### ISSUE TITLE
쿼리스트링을 변경하는 동작을 할 때도 라우팅하는 것으로 인식함

### ISSUE THREAD

**Issue by saengmotmi** [feedoong/feedoong-frontend#139]
![image](https://user-images.githubusercontent.com/35240142/214754570-99d016f8-3020-4a7f-b2f2-127254796988.png)

이러한 동작이 당연하긴 한데 오버헤드가 될 수 있는지는 확인 필요

**Comment by Yeongjae-Shin** [comment]
shallow routing으로 url만 변경시키면 되지 않나요? 🤔 react-query에서 쿼리 파라미터 값을 읽어서 리페치 하도록 해도 될 것 같은데

**Comment by saengmotmi** [comment]
> shallow routing으로 url만 변경시키면 되지 않나요? 🤔 react-query에서 쿼리 파라미터 값을 읽어서 리페치 하도록 해도 될 것 같은데

오호 shallow routing 할 일이 없어서 생각을 못했는데 그래도 되겠네요
