### ISSUE TITLE
홈피드에서 게시글 저장을 누른 뒤 내가 저장한 게시물 페이지로 이동 시 업데이트 안되는 문제

### ISSUE THREAD

**Issue by jamessoun93** [feedoong/feedoong-frontend#33]
내가 저장한 게시물 페이지 이동 시 다시 서버 호출이 필요해 보이네요.
 
+ 반대로, 홈피드에서 저장된 게시물 저장 해제 (unlike)를 누른 뒤 내가 저장한 게시물 페이지로 이동해도 업데이트 안됨.

**Comment by saengmotmi** [comment]
react query 캐시 무효화 로직 문제로 known issue - 현재 수정 중

**Comment by saengmotmi** [comment]
#36 에서 해결됨
