### ISSUE TITLE
로딩 컴포넌트 그리드타입 이슈

### ISSUE THREAD

**Issue by Yeongjae-Shin** [feedoong/feedoong-frontend#70]
- 그리드형 뷰로 볼 때 로딩 컴포넌트 노출 시 그리드 카드 형태로 노출되는 이슈가 있음
  - 뷰 타입과 관계 없이 일정한 너비의 로딩 컴포넌트 노출 필요
<img width="886" alt="스크린샷 2022-11-26 오후 5 10 08" src="https://user-images.githubusercontent.com/60685930/204079093-a35173b1-b9ea-4002-9fc4-9e9f28508618.png">

**Comment by saengmotmi** [comment]
#75 에서 해결
